let activeClientId='';
async function initDetail(){if(!(await protectPage()))return;activeClientId=new URLSearchParams(location.search).get('id')||'';await renderDetail()}
async function renderDetail(){try{const d=await api.clientDetail(activeClientId),c=d.client;
const analysisButton=document.getElementById('startAnalysisButton');
if(analysisButton)analysisButton.href=`analysis.html?client_id=${encodeURIComponent(activeClientId)}`;detailName.textContent=c.full_name;detailContact.textContent=[c.whatsapp,c.email].filter(Boolean).join(' · ')||'Kontak belum diisi';creditNumber.textContent=Number(c.consultation_credit||0);clientMeta.innerHTML=`<div class="meta-row"><span>Kode Client</span><span>${esc(c.client_code)}</span></div><div class="meta-row"><span>WhatsApp</span><span>${esc(c.whatsapp||'-')}</span></div><div class="meta-row"><span>Email</span><span>${esc(c.email||'-')}</span></div><div class="meta-row"><span>Terdaftar</span><span>${fmtDate(c.created_at)}</span></div>`;clientBookings.innerHTML=d.consultations.map(x=>`<div class="item"><div class="avatar"><i data-lucide="calendar-check"></i></div><div class="copy"><strong>${esc(x.service_name_snapshot)}</strong><small>${esc(x.consultation_no)} · ${fmtDate(x.created_at)}</small></div><span class="badge ${badgeClass(x.consultation_status)}">${statusLabel(x.consultation_status)}</span></div>`).join('')||'<div class="empty">Belum ada konsultasi.</div>';clientPayments.innerHTML=d.payments.map(p=>{
 const number=p.invoice_no||p.consultations?.consultation_no||'-';
 const service=p.consultations?.service_name_snapshot||'Konsultasi';
 const date=p.status==='paid'?(p.paid_at||p.updated_at||p.created_at):(p.created_at||p.updated_at);
 return `<div class="item"><div class="avatar"><i data-lucide="wallet-cards"></i></div><div class="copy"><strong>${esc(number)}</strong><small>${rupiah(p.amount)} · ${esc(service)}<br>${p.status==='paid'?'Dibayar':'Dibuat'} ${fmtDate(date)}</small></div><span class="badge ${badgeClass(p.status)}">${statusLabel(p.status)}</span></div>`;
}).join('')||'<div class="empty">Belum ada pembayaran.</div>';clientHistory.innerHTML=d.activities.map(h=>`<div class="timeline-item"><strong>${esc(h.description)}</strong><small>${esc(h.event_type)}<br>${fmtDate(h.created_at)}</small></div>`).join('')||'<div class="empty">Belum ada aktivitas.</div>';if(window.lucide)lucide.createIcons()}catch(err){alert('Gagal memuat detail client: '+err.message);location.href='clients.html'}}
async function changeCredit(amount){try{const c=await api.getClient(activeClientId),next=Math.max(0,Number(c.consultation_credit||0)+Number(amount));await api.updateClient(activeClientId,{consultation_credit:next});await api.log({client_id:activeClientId,event_type:'credit_updated',description:`Consultation credit ${amount>0?'ditambah':'dikurangi'} ${Math.abs(amount)}. Sisa ${next}.`});await renderDetail()}catch(err){alert(err.message)}}
document.addEventListener('DOMContentLoaded',initDetail);
