let activeClientId='',activeClientPayments=[],activeDetail=null;
async function initDetail(){if(!(await protectPage()))return;activeClientId=new URLSearchParams(location.search).get('id')||'';bindWorkspace();await renderDetail()}
function bindWorkspace(){document.getElementById('workspaceTabs').addEventListener('click',e=>{const b=e.target.closest('button[data-tab]');if(!b)return;document.querySelectorAll('.workspace-tabs button').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.workspace-panel').forEach(x=>x.classList.toggle('active',x.dataset.panel===b.dataset.tab))});noteForm.addEventListener('submit',saveNote);followupForm.addEventListener('submit',saveFollowup);documentForm.addEventListener('submit',uploadDocument)}
function clientPayment(key){return activeClientPayments.find(p=>String(p.id)===String(key))}
async function clientInvoice(key){const p=clientPayment(key);if(!p)return alert('Data pembayaran tidak ditemukan.');try{await window.cfDocuments.downloadInvoice({...p,client_name:activeDetail?.client?.full_name,client_email:activeDetail?.client?.email,client_phone:activeDetail?.client?.whatsapp})}catch(e){alert(e.message)}}
async function clientReceipt(key){const p=clientPayment(key);if(!p)return alert('Data pembayaran tidak ditemukan.');try{await window.cfDocuments.downloadReceipt({...p,client_name:activeDetail?.client?.full_name,client_email:activeDetail?.client?.email,client_phone:activeDetail?.client?.whatsapp})}catch(e){alert(e.message)}}
function metaRows(c){return `<div class="meta-row"><span>WhatsApp</span><span>${esc(c.whatsapp||'-')}</span></div><div class="meta-row"><span>Email</span><span>${esc(c.email||'-')}</span></div><div class="meta-row"><span>Terdaftar</span><span>${fmtDate(c.created_at)}</span></div>`}
function renderWorkflow(d){const paid=d.payments.some(p=>p.status==='paid'),scheduled=d.consultations.some(c=>c.scheduled_at),completed=d.consultations.some(c=>c.consultation_status==='completed'),docs=(d.activities||[]).some(a=>a.event_type==='document_uploaded'),follow=(d.activities||[]).some(a=>a.event_type==='follow_up_created');const rows=[['Booking diterima',d.consultations.length>0],['Invoice dibuat',d.payments.length>0],['Pembayaran diterima',paid],['Jadwal dibuat',scheduled],['Konsultasi selesai',completed],['Dokumen tersimpan',docs],['Follow-up dibuat',follow]];workflowList.innerHTML=rows.map(([t,ok])=>`<div class="workflow-row ${ok?'done':''}"><span><i data-lucide="${ok?'circle-check':'circle'}"></i></span><strong>${t}</strong><small>${ok?'Selesai':'Belum'}</small></div>`).join('')}
function activityMeta(a){return a.metadata&&typeof a.metadata==='object'?a.metadata:{}}
function renderNotes(activities){const rows=activities.filter(a=>a.event_type==='internal_note');clientNotes.innerHTML=rows.map(a=>{const m=activityMeta(a);return `<article class="workspace-entry"><div><strong>${esc(m.title||'Catatan')}</strong><small>${fmtDate(a.created_at)}</small></div><p>${esc(m.body||a.description)}</p></article>`}).join('')||'<div class="empty">Belum ada catatan internal.</div>'}
function renderFollowups(activities){const rows=activities.filter(a=>a.event_type==='follow_up_created');clientFollowups.innerHTML=rows.map(a=>{const m=activityMeta(a);return `<article class="workspace-entry"><div><strong>${esc(m.title||'Follow-up')}</strong><span class="badge ${m.done?'green':'orange'}">${m.done?'Selesai':esc(m.date||'-')}</span></div><p>${esc(m.note||'Tanpa catatan')}</p>${!m.done?`<button class="btn btn-secondary" onclick="completeFollowup('${a.id}')">Tandai Selesai</button>`:''}</article>`}).join('')||'<div class="empty">Belum ada follow-up.</div>'}
function renderDocuments(activities){const rows=activities.filter(a=>a.event_type==='document_uploaded');clientDocuments.innerHTML=rows.map(a=>{const m=activityMeta(a);return `<article class="document-card"><span><i data-lucide="file-text"></i></span><div><strong>${esc(m.title||'Dokumen')}</strong><small>${esc(m.category||'Lainnya')} · ${fmtDate(a.created_at)}</small></div>${m.url?`<a href="${esc(m.url)}" target="_blank" rel="noopener"><i data-lucide="download"></i></a>`:''}</article>`}).join('')||'<div class="empty">Belum ada dokumen internal.</div>'}
async function renderDetail(){try{const d=await api.clientDetail(activeClientId);activeDetail=d;activeClientPayments=d.payments||[];const c=d.client,paid=activeClientPayments.filter(p=>p.status==='paid').reduce((s,p)=>s+Number(p.amount||0),0),docs=d.activities.filter(a=>a.event_type==='document_uploaded'),next=d.activities.filter(a=>a.event_type==='follow_up_created'&&!activityMeta(a).done).map(a=>activityMeta(a).date).filter(Boolean).sort()[0];detailName.textContent=snapshotName.textContent=c.full_name;detailContact.textContent=[c.whatsapp,c.email].filter(Boolean).join(' · ')||'Kontak belum diisi';snapshotAvatar.textContent=(c.full_name||'C').trim().charAt(0).toUpperCase();snapshotMember.textContent='Member sejak '+new Intl.DateTimeFormat('id-ID',{month:'long',year:'numeric'}).format(new Date(c.created_at));snapshotConsultations.textContent=d.consultations.length;snapshotRevenue.textContent=rupiah(paid);snapshotDocuments.textContent=docs.length;snapshotFollowup.textContent=next?new Intl.DateTimeFormat('id-ID',{day:'2-digit',month:'short'}).format(new Date(next+'T00:00:00')):'-';creditNumber.textContent=Number(c.consultation_credit||0);clientCodeBadge.textContent=c.client_code||'-';clientMeta.innerHTML=metaRows(c);startAnalysisButton.href=`analysis.html?client_id=${encodeURIComponent(activeClientId)}`;clientBookings.innerHTML=d.consultations.slice(0,5).map(x=>`<div class="item"><div class="avatar"><i data-lucide="calendar-check"></i></div><div class="copy"><strong>${esc(x.service_name_snapshot)}</strong><small>${esc(x.consultation_no)} · ${fmtDate(x.created_at)}</small></div><span class="badge ${badgeClass(x.consultation_status)}">${statusLabel(x.consultation_status)}</span></div>`).join('')||'<div class="empty">Belum ada konsultasi.</div>';clientPayments.innerHTML=activeClientPayments.map(p=>`<div class="billing-card"><div><strong>${esc(p.invoice_no||p.consultations?.consultation_no||'-')}</strong><small>${esc(p.consultations?.service_name_snapshot||'Konsultasi')} · ${rupiah(p.amount)}</small></div><span class="badge ${badgeClass(p.status)}">${statusLabel(p.status)}</span><div class="actions"><button class="btn btn-secondary" onclick="clientInvoice('${p.id}')">Invoice</button>${p.status==='paid'?`<button class="btn btn-primary" onclick="clientReceipt('${p.id}')">Receipt</button>`:''}</div></div>`).join('')||'<div class="empty">Belum ada pembayaran.</div>';clientHistory.innerHTML=d.activities.map(a=>`<div class="timeline-item"><strong>${esc(a.description)}</strong><small>${fmtDate(a.created_at)}</small></div>`).join('')||'<div class="empty">Belum ada aktivitas.</div>';renderWorkflow(d);renderNotes(d.activities);renderFollowups(d.activities);renderDocuments(d.activities);if(window.lucide)lucide.createIcons()}catch(e){alert('Gagal memuat workspace: '+e.message)}}
async function changeCredit(v){try{const c=await api.getClient(activeClientId),next=Math.max(0,Number(c.consultation_credit||0)+Number(v));await api.updateClient(activeClientId,{consultation_credit:next});await api.log({client_id:activeClientId,event_type:'credit_updated',description:`Consultation credit diperbarui menjadi ${next}`});await renderDetail()}catch(e){alert(e.message)}}
async function saveNote(e){e.preventDefault();try{await api.addClientActivity(activeClientId,'internal_note',noteTitle.value.trim(),{title:noteTitle.value.trim(),body:noteBody.value.trim()});e.target.reset();await renderDetail()}catch(err){alert(err.message)}}
async function saveFollowup(e){e.preventDefault();try{await api.addClientActivity(activeClientId,'follow_up_created',`Follow-up: ${followupTitle.value.trim()}`,{date:followupDate.value,title:followupTitle.value.trim(),note:followupNote.value.trim(),done:false});e.target.reset();await renderDetail()}catch(err){alert(err.message)}}
async function completeFollowup(id){try{const a=activeDetail.activities.find(x=>String(x.id)===String(id)),m={...activityMeta(a),done:true,completed_at:new Date().toISOString()};await api.updateActivity(id,{description:`Follow-up selesai: ${m.title||''}`,metadata:m});await renderDetail()}catch(e){alert(e.message)}}
function openDocumentForm(){documentModal.hidden=false;if(window.lucide)lucide.createIcons()}function closeDocumentForm(){documentModal.hidden=true;documentForm.reset()}
async function uploadDocument(e){e.preventDefault();const btn=e.submitter,file=documentFile.files[0];if(!file)return;try{btn.disabled=true;btn.textContent='Mengupload...';await api.uploadClientDocument(activeClientId,file,{title:documentTitle.value.trim(),category:documentCategory.value});closeDocumentForm();await renderDetail()}catch(err){alert('Upload gagal: '+err.message)}finally{btn.disabled=false;btn.textContent='Upload Dokumen'}}
document.addEventListener('DOMContentLoaded',initDetail);