const med = id => document.getElementById(id);
let medRows = [], medSelected = null;
const MED_PROFILE = ["Timestamp","Nomor Registrasi","Email","Nama Pemegang Polis","Nomor Handphone Pemegang Polis","Nama Tertanggung","Nomor Handphone Tertanggung","Jenis Kelamin Tertanggung","Tanggal Lahir Tertanggung","Nama Ibu Kandung Tertanggung","Tinggi Badan Tertanggung","Berat Badan Tertanggung","Nama Pembayar Premi","Hubungan Calon Tertanggung dengan Calon Pembayar Premi","Penghasilan Kotor Tahunan","Sumber Penghasilan","Nama Perusahaan (Tempat Kerja)","Jenis Usaha","Bidang Usaha","Jabatan","Uraian Pekerjaan (Bagian)"];
const MED_SYSTEM = ["Timestamp","Nomor Registrasi","Status","Sudah Dibaca","Terakhir Dibaca","Folder Dokumen"];

function medEsc(v){return String(v??'').replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]))}
async function medCall(action,payload={}){const {data:{session}}=await cfSupabase.auth.getSession();if(!session?.access_token)throw new Error('Sesi CRM berakhir. Silakan login kembali.');const response=await fetch('/api/medical-history',{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${session.access_token}`},body:JSON.stringify({action,...payload})});const text=await response.text();let data;try{data=JSON.parse(text)}catch{throw new Error('Respons server modul tidak valid.')}if(!response.ok||!data.success)throw new Error(data.message||'Proses gagal.');return data}
function medShowContent(){med('medicalLoading').hidden=true;med('medicalContent').hidden=false}
function medShowError(message){med('medicalLoading').hidden=true;med('medicalContent').hidden=false;med('medicalPageError').textContent=message;med('medicalPageError').hidden=false}
async function medLoad(){med('medicalLoading').hidden=false;med('medicalContent').hidden=true;try{const data=await medCall('listData');medRows=data.rows||[];medShowContent();medStats();medRender();med('medicalPageError').hidden=true}catch(error){medShowError(error.message)}}
function medDateKey(value){if(!value)return'';const d=new Date(value);if(Number.isNaN(d.getTime()))return String(value).slice(0,10);return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Jakarta'}).format(d)}
function medStats(){const today=medDateKey(new Date());med('medicalTotal').textContent=medRows.length;med('medicalToday').textContent=medRows.filter(r=>medDateKey(r.Timestamp)===today).length;med('medicalNew').textContent=medRows.filter(r=>(r.Status||'Baru')==='Baru').length}
function medInitials(name){return String(name||'N').split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join('').toUpperCase()}
function medStatusClass(status){return {'Baru':'blue','Sedang Dicek':'orange','Dokumen Kurang':'red','Sudah Lengkap':'green','Selesai':'dark'}[status]||'blue'}
function medRender(){const q=med('medicalSearch').value.trim().toLowerCase(),status=med('medicalStatusFilter').value;const rows=medRows.filter(r=>(!q||Object.values(r).join(' ').toLowerCase().includes(q))&&(status==='all'||(r.Status||'Baru')===status));med('medicalEmpty').hidden=rows.length>0;med('medicalList').innerHTML=rows.map(r=>{const reg=r['Nomor Registrasi']||'',name=r['Nama Tertanggung']||'-',st=r.Status||'Baru';return `<button class="medical-row" data-med-reg="${medEsc(reg)}" type="button"><span class="medical-avatar">${medEsc(medInitials(name))}</span><span class="medical-row-main"><strong>${medEsc(name)}</strong><small>${medEsc(reg)} · ${medEsc(r.Timestamp||'-')}</small><em>${medEsc(r['Nomor Handphone Tertanggung']||r.Email||'-')}</em></span><span class="medical-row-side"><b class="medical-status ${medStatusClass(st)}">${medEsc(st)}</b><i data-lucide="chevron-right"></i></span></button>`}).join('');document.querySelectorAll('[data-med-reg]').forEach(b=>b.onclick=()=>medOpen(b.dataset.medReg));if(window.lucide)lucide.createIcons()}
function medDocs(row){const out=[];Object.entries(row||{}).forEach(([key,value])=>{const urls=String(value||'').split(/\s+/).filter(x=>/^https?:\/\//i.test(x));if(urls.length&&(/foto|dokumen|ktp|kartu keluarga|buku bank|lampiran|folder/i.test(key)||/^https?:\/\/(drive|docs)\.google\.com/i.test(String(value).trim())))urls.forEach(url=>out.push({key,url}))});return out}
async function medOpen(reg){try{const data=await medCall('getDetail',{registrationNumber:reg});medSelected=data.row;const name=medSelected['Nama Tertanggung']||'Nasabah';med('medicalDetailTitle').textContent=name;med('medicalDetailReg').textContent=reg;med('medicalDetailMeta').textContent=medSelected.Timestamp||'';med('medicalDetailStatus').value=medSelected.Status||'Baru';medRenderProfile();medRenderAnswers();medRenderDocuments();medTab('profile');med('medicalModal').hidden=false;med('medicalModal').setAttribute('aria-hidden','false');document.body.classList.add('medical-modal-open');if(window.lucide)lucide.createIcons()}catch(error){alert(error.message)}}
function medItem(k,v){return `<article class="medical-detail-item"><small>${medEsc(k)}</small><div>${/^https?:\/\//i.test(String(v).trim())?`<a href="${medEsc(v)}" target="_blank" rel="noopener">Buka tautan</a>`:medEsc(v)}</div></article>`}
function medRenderProfile(){const entries=MED_PROFILE.filter(k=>String(medSelected[k]||'').trim());med('medical-tab-profile').innerHTML=entries.length?entries.map(k=>medItem(k,medSelected[k])).join(''):'<p class="medical-tab-empty">Data nasabah belum tersedia.</p>'}
function medRenderAnswers(){const docs=new Set(medDocs(medSelected).map(d=>d.key));const entries=Object.entries(medSelected).filter(([k,v])=>String(v||'').trim()&&!MED_PROFILE.includes(k)&&!MED_SYSTEM.includes(k)&&!docs.has(k));med('medical-tab-answers').innerHTML=entries.length?entries.map(([k,v])=>medItem(k,v)).join(''):'<p class="medical-tab-empty">Jawaban belum tersedia.</p>'}
function medDriveId(url){return String(url).match(/\/file\/d\/([\w-]+)/)?.[1]||String(url).match(/[?&]id=([\w-]+)/)?.[1]||''}
function medRenderDocuments(){const folder=medSelected['Folder Dokumen']||'';const docs=medDocs(medSelected).filter(d=>d.key!=='Folder Dokumen');let html=folder?`<a class="medical-doc folder" href="${medEsc(folder)}" target="_blank" rel="noopener"><i data-lucide="folder-open"></i><span><small>Folder Dokumen</small><strong>Buka seluruh dokumen</strong></span></a>`:'';html+=docs.map(d=>{const id=medDriveId(d.url),download=id?`https://drive.google.com/uc?export=download&id=${encodeURIComponent(id)}`:d.url;return `<article class="medical-doc"><i data-lucide="file-image"></i><span><small>${medEsc(d.key)}</small><strong>Dokumen nasabah</strong></span><div><a href="${medEsc(d.url)}" target="_blank" rel="noopener">Lihat</a><a href="${medEsc(download)}" target="_blank" rel="noopener">Unduh</a></div></article>`}).join('');med('medical-tab-documents').innerHTML=html||'<p class="medical-tab-empty">Tidak ada dokumen.</p>'}
function medTab(name){document.querySelectorAll('[data-medical-tab]').forEach(b=>b.classList.toggle('active',b.dataset.medicalTab===name));document.querySelectorAll('.medical-tab-panel').forEach(p=>p.classList.toggle('active',p.id===`medical-tab-${name}`))}
function medClose(){med('medicalModal').hidden=true;med('medicalModal').setAttribute('aria-hidden','true');document.body.classList.remove('medical-modal-open');medSelected=null}
async function medSaveStatus(){if(!medSelected)return;const btn=med('medicalSaveStatus');btn.disabled=true;try{const reg=medSelected['Nomor Registrasi'],status=med('medicalDetailStatus').value;await medCall('updateStatus',{registrationNumber:reg,status});medSelected.Status=status;const row=medRows.find(r=>r['Nomor Registrasi']===reg);if(row)row.Status=status;medStats();medRender();alert('Status berhasil diperbarui.')}catch(e){alert(e.message)}finally{btn.disabled=false}}
function medWhatsapp(){const p=String(medSelected?.['Nomor Handphone Tertanggung']||medSelected?.['Nomor Handphone Pemegang Polis']||'').replace(/\D/g,'');if(!p)return alert('Nomor WhatsApp tidak tersedia.');const n=p.startsWith('0')?'62'+p.slice(1):p.startsWith('62')?p:'62'+p;window.open('https://wa.me/'+n,'_blank','noopener')}
function medFolder(){const url=medSelected?.['Folder Dokumen'];if(!url)return alert('Folder tidak tersedia.');window.open(url,'_blank','noopener')}
async function medPdf(){if(!medSelected)return;const btn=med('medicalPdf');btn.disabled=true;try{const reg=medSelected['Nomor Registrasi'],data=await medCall('exportPdf',{registrationNumber:reg});const binary=atob(data.base64),bytes=new Uint8Array(binary.length);for(let i=0;i<binary.length;i++)bytes[i]=binary.charCodeAt(i);const url=URL.createObjectURL(new Blob([bytes],{type:data.mimeType||'application/pdf'})),a=document.createElement('a');a.href=url;a.download=data.fileName||`Laporan_${reg}.pdf`;a.click();setTimeout(()=>URL.revokeObjectURL(url),2000)}catch(e){alert(e.message)}finally{btn.disabled=false}}
async function medDelete(){if(!medSelected)return;const reg=medSelected['Nomor Registrasi'],name=medSelected['Nama Tertanggung']||'Nasabah';if(!confirm(`Hapus pengajuan ${name} (${reg})?\nData dan folder dokumen akan dipindahkan ke Sampah.`))return;try{await medCall('deleteData',{registrationNumber:reg});medClose();await medLoad();alert('Pengajuan berhasil dihapus.')}catch(e){alert(e.message)}}

document.addEventListener('DOMContentLoaded',async()=>{if(!(await protectPage()))return;med('medicalSearch').oninput=medRender;med('medicalStatusFilter').onchange=medRender;med('refreshMedical').onclick=medLoad;med('closeMedicalModal').onclick=medClose;med('medicalModalBackdrop').onclick=medClose;med('medicalSaveStatus').onclick=medSaveStatus;med('medicalWhatsApp').onclick=medWhatsapp;med('medicalFolder').onclick=medFolder;med('medicalPdf').onclick=medPdf;med('medicalDelete').onclick=medDelete;document.querySelectorAll('[data-medical-tab]').forEach(b=>b.onclick=()=>medTab(b.dataset.medicalTab));if(window.lucide)lucide.createIcons();await medLoad()});
